name: vos_app
description: A production-ready Flutter application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI/UX
  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  lottie: ^3.1.2
  font_awesome_flutter: ^10.8.0

  # State Management
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  equatable: ^2.0.5

  # Navigation
  go_router: ^14.6.2

  # Dependency Injection
  get_it: ^8.0.2
  injectable: ^2.5.0

  # Network
  dio: ^5.7.0
  retrofit: ^4.4.1
  pretty_dio_logger: ^1.4.0
  connectivity_plus: ^6.1.0

  # Local Storage
  shared_preferences: ^2.3.3
  flutter_secure_storage: ^9.2.2
  hive_flutter: ^1.1.0

  # Utilities
  intl: ^0.20.0
  uuid: ^4.5.1
  flutter_dotenv: ^5.2.1
  logger: ^2.5.0
  permission_handler: ^11.3.1
  url_launcher: ^6.3.1
  share_plus: ^10.1.2

  # Forms & Validation
  flutter_form_builder: ^10.2.0
  form_builder_validators: ^11.0.0

  # Image & Media
  image_picker: ^1.1.2

  # JSON Serialization
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting
  flutter_lints: ^5.0.0

  # Code Generation
  build_runner: ^2.4.13
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  injectable_generator: ^2.6.2
  retrofit_generator: ^9.1.4

  # Testing
  bloc_test: ^9.1.7
  mocktail: ^1.0.4

  # Dev Tools
  flutter_launcher_icons: ^0.14.2
  flutter_native_splash: ^2.4.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - .env
    - .env.dev
    - .env.staging
    - .env.production

  # fonts:
  #   - family: AppIcons
  #     fonts:
  #       - asset: assets/fonts/app_icons.ttf

# flutter_native_splash:
#   color: "#FFFFFF"
#   image: assets/images/splash.png
#   android: true
#   ios: true
#   web: true

# flutter_launcher_icons:
#   android: true
#   ios: true
#   image_path: "assets/icons/app_icon.png"
#   adaptive_icon_background: "#FFFFFF"
#   adaptive_icon_foreground: "assets/icons/app_icon_adaptive.png"